[project]
name = "pypiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ray[default]>=2.40.0",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
